### ISSUE TITLE
equal cost ordering

### ISSUE THREAD

**Issue by mutsurhea** [benediktwerner/vampire-survivors-power-up-calculator#1]
i dont know how to leave comments on github, so im using Issues tab

e.g. duration, speed, area
there order doesn't matter
i think it would be better if they were all numbered there same
e.g.
12 movspeed
13 duration/speed/area
16 max hp
or
12 movspd
13 duration
13 speed
13 area
16 max hp
or
12 movspd
13a duration
13b speed
13c area
16 max hp

**Comment by benediktwerner** [comment]
Sure, I guess.
