### ISSUE TITLE
I think the order of calculation is wrong

### ISSUE THREAD

**Issue by waterfall531** [benediktwerner/vampire-survivors-power-up-calculator#2]
I think the amount calculation should be

```js
calLevelUpNeed = (baseSkillValue, baseSkillLevel, pick) => {
    return baseSkillValue * ((pick - 1) / 10 + 1) * baseSkillLevel;
};
```

So the least amount spent should be the most expensive, starting from the most expensive
For example, if we move Skip to order 4, it should only cost 1300 instead of 2600

Remind me of any mistakes
Thx

**Comment by benediktwerner** [comment]
No idea what you're saying but I'm fairly confident all the calculations are correct. You can easily verify it by trying it out in-game and comparing it to what was calculated.
