### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by Cheetah-shooter** [benediktwerner/vampire-survivors-power-up-calculator#23]
Since a few updates ago, all of the powerups have been added and you no longer have to update them anymore. Can you add the final tier for Reroll and Skip (and add the notches back)?

**Comment by benediktwerner** [comment]
Tbh given that the order is now irrelevant, I'm not really sure how useful it still is but added them. I don't have an up-to-date save game anymore to check though so I hope the values are correct.
