### ISSUE TITLE
Encode the selection in URL to allow sharing builds.

### ISSUE THREAD

**Issue by jaskij** [benediktwerner/vampire-survivors-power-up-calculator#5]
As the title says - encode the choices? Then update the URL (or allow copying it?), so that it can be copied and shared. Would require also decoding it on load, if present.

The point of this is to allow easy sharing of builds with a permalink.

An example encoding would be a string of digits - one per skill. This easily allows representing levels in the range 0-61, but could be extended further if needed.

**Comment by benediktwerner** [comment]
Sure.

Implemented in 8f239cd.

**Comment by jaskij** [comment]
Thank you!
